extern float value;
extern u8 fp,fps;
extern struct MenuItem *MenuPoint;
void menu_init(void);
void menu(void);
void OLED_showclear(void);
int min(int a,int b);
void display(struct MenuItem * MenuPoint,int selectItem_current,int selectItem_hidden);
void start(void);
void MonitoringMODE(void);
void ControlMode(void);
void poem1(void);
void logo1(void);
void logo2(void);
void Circle1(void);
void Circle2(void);
void ellipse1(void);
void rocker(void);
